### PR TITLE
1.12: Avoid deprecated YamlConfiguration.loadConfiguration(InputStream)

### PR DESCRIPTION
**Pull request by colajunkie13**
Use File instead of InputStream for loadConfiguration.

### CODE REVIEW

**Comment by graywolf336** [comment]
test this please

**Comment by graywolf336** [comment]
ok to test

**Comment by graywolf336** [comment]
Thanks for the pull request, I'm looking into why it failed as it failed to start

**Comment by graywolf336** [comment]
retest this please

**Comment by graywolf336** [comment]
retest this please

**Comment by graywolf336** [comment]
retest this please

**Comment by graywolf336** [comment]
@colajunkie13 Did you run the unit tests successfully?

**Comment by colajunkie13** [comment]
I think i found the problem in the test code:
Lines 119 and 120 in TestInstanceCreator.java:
 ```
doReturn(getClass().getClassLoader().getResourceAsStream("config.yml")).when(main).getResource("config.yml");
doReturn(getClass().getClassLoader().getResourceAsStream("locales/en.yml")).when(main).getResource("locales/en.yml");
```

Since i'm not using getResource() anymore, the language doesn't get loaded for the test.
Works like a charm on both windows and linux servers though.

Possible ways around this:
- Use `loadConfiguration(new InputStreamReader(pl.getResource("locales/en.yml")))` instead of my `loadConfiguration(new File(pl.getDataFolder(),"locales/en.yml")))` (works just as well, passes all the tests, i just prefer File)
- Rewrite test code

**Comment by colajunkie13** [comment]
I switched to loadConfiguration(InputStream). Tests should pass now.

**Comment by graywolf336** [comment]
As the CI is failing due to an update to the CI, I'll try this out tonight and get it merged. Thanks for this!

**Pull request merged**
